CREATE TABLE IF NOT EXISTS `rekon_master` (
  `rm_id` int(11) NOT NULL AUTO_INCREMENT,
  `pegawai_id` int(11) NOT NULL,
`f1` datetime not null,
`f2` datetime not null,
`f3` datetime not null,
`f4` datetime not null,
`f5` datetime not null,
`f6` datetime not null,
`f7` datetime not null,
`f8` datetime not null,
`f9` datetime not null,
`f10` datetime not null,
`f11` datetime not null,
`f12` datetime not null,
`f13` datetime not null,
`f14` datetime not null,
`f15` datetime not null,
`f16` datetime not null,
`f17` datetime not null,
`f18` datetime not null,
`f19` datetime not null,
`f20` datetime not null,
`f21` datetime not null,
`f22` datetime not null,
`f23` datetime not null,
`f24` datetime not null,
`f25` datetime not null,
`f26` datetime not null,
`f27` datetime not null,
`f28` datetime not null,
`f29` datetime not null,
`f30` datetime not null,
`f31` datetime not null,
  PRIMARY KEY (`rm_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;