CREATE TABLE IF NOT EXISTS `rekon_master` (
  `rm_id` int(11) NOT NULL AUTO_INCREMENT,
  `pegawai_id` int(11) NOT NULL,
  `f1` time not null,
  `f2` time not null,
  `f3` time not null,
  `f4` time not null,
  `f5` time not null,
  `f6` time not null,
  `f7` time not null,
  `f8` time not null,
  `f9` time not null,
  `f10` time not null,
  `f11` time not null,
  `f12` time not null,
  `f13` time not null,
  `f14` time not null,
  `f15` time not null,
  `f16` time not null,
  `f17` time not null,
  `f18` time not null,
  `f19` time not null,
  `f20` time not null,
  `f21` time not null,
  `f22` time not null,
  `f23` time not null,
  `f24` time not null,
  `f25` time not null,
  `f26` time not null,
  `f27` time not null,
  `f28` time not null,
  `f29` time not null,
  `f30` time not null,
  `f31` time not null
  PRIMARY KEY (`pd_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;